language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn prep
script:
  - yarn build
  - mkdir build
  - cp -r dist build/dist
  - cp -r saved_model_* build/
  - cp -r images build/images
  - cp index.html build/index.html
  - cp bootstrap.min.css build/bootstrap.min.css
  - cp style.css build/style.css
  - cp header-bg.jpg build/header-bg.jpg
  - cp logo_horizontal.png build/logo_horizontal.png
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  local_dir: build
  edge: true
  on:
    branch: main
